### PR TITLE
add support for https proxy

### PR DESCRIPTION
**Pull request by rodriguezsergio**

### CODE REVIEW

**Comment by rodriguezsergio** [comment]
It appears to be working fine for me, except when the stash is active, I see 'expires => never' instead of the 5 minutes I specified. As soon as I update 

https://github.com/needle-cookbooks/chef-sensu-handler/pull/2/files#diff-b7013de30524ec3746532afa5dfaaccfR21

to read "expire_at"  (see #1 ), it ends up breaking the Stashes page on the Sensu Admin interface haha. I'll live without the expiration variable until I figure out what's breaking it.

**Comment by rodriguezsergio** [comment]
@cwjohnston Get a chance to look at this yet?

**Comment by cwjohnston** [comment]
@srodrig0209, thanks for the PR, and I apologize that it's taken me so long to look at it. 

Would you mind checking out this change to what you've done? https://github.com/needle-cookbooks/chef-sensu-handler/compare/pr%2F2...https-api-support

When we aren't passing as many arguments to the silence_client and unsilence_client methods, I think the code is easier to read and expand upon.

**Comment by rodriguezsergio** [comment]
@cwjohnston Haven't had the time to look at this. I think I tried to pass in a hash, but was unsuccessful for some reason. I'll see if I can check this out tomorrow at work.

**Comment by rodriguezsergio** [comment]
Okay, I updated the README, attributes, and default recipe along with your changes to the handler file. Tested it out and it works fine.

**Comment by rodriguezsergio** [comment]
Forgot to commit this ...

**Pull request closed without merging**
